# Generated by Django 2.1.3 on 2019-01-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brumadinho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Full name of the found people.', max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=None, help_text='Gender of the found people.', max_length=2, null=True)),
                ('status_condition', models.CharField(blank=True, choices=[('Alive', 'Alive'), ('Dead', 'Dead')], default=None, help_text='Status condition of the found people.', max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='visitedlocation',
            name='encounter_number',
            field=models.IntegerField(default=0, help_text='Number of people found in this location.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitedlocation',
            name='visitation_date',
            field=models.DateTimeField(blank=True, help_text='Datetime of the location analysis.', null=True),
        ),
        migrations.AlterField(
            model_name='visitedlocation',
            name='location',
            field=models.ForeignKey(help_text='Geoposition of the visited area.', on_delete=django.db.models.deletion.PROTECT, to='brumadinho.Geolocation'),
        ),
        migrations.AlterField(
            model_name='visitedlocation',
            name='reference',
            field=models.CharField(help_text='Reference and information.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='geolocation',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AddField(
            model_name='foundpeople',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Found location.', null=True, on_delete=django.db.models.deletion.PROTECT, to='brumadinho.Geolocation'),
        ),
    ]
