# Generated by Django 2.1.3 on 2019-01-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brumadinho', '0002_auto_20190129_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='radius',
            field=models.FloatField(default=1, help_text='Radial área range.'),
        ),
    ]
